NeoXamPiDev-web/src/main/java/tn/esprit/neoxam/managedbeans/Document/AutorisationDeCongeBean.java
package tn.esprit.neoxam.managedbeans.Document;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.Serializable;
import java.net.MalformedURLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;

import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.FontSelector;
import com.itextpdf.text.pdf.PdfWriter;

import tn.esprit.entities.AutorisationConge;
import tn.esprit.entities.Conge;
import tn.esprit.entities.Employe;
import tn.esprit.service.employe.impl.EmployeServiceImpl;
import tn.esprit.services.Document.Impl.AutorisationCongeServiceImpl;


@ManagedBean(name="AutorisationCongeBean")
public class AutorisationDeCongeBean implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	public AutorisationDeCongeBean() {
		// TODO Auto-generated constructor stub
	}
	
	
	private Conge conge;
	private List<Conge> conges = new ArrayList<>();
	private Employe employe;
	private int idConge;
	private String filleNaMe;
	private static AutorisationConge autoris;


	
	
	public Conge getConge() {
		return conge;
	}

	public List<Conge> getConges() {
		return conges;
	}

	public Employe getEmploye() {
		return employe;
	}

	public int getIdConge() {
		return idConge;
	}

	public void setConge(Conge conge) {
		this.conge = conge;
	}

	public void setConges(List<Conge> conges) {
		this.conges = conges;
	}

	public void setEmploye(Employe employe) {
		this.employe = employe;
	}

	public void setIdConge(int idConge) {
		this.idConge = idConge;
	}


	@EJB
	AutorisationCongeServiceImpl autorisationCongeServiceImpl;
	
	@EJB
	EmployeServiceImpl employeServiceImpl;
	
	public  List<Conge> allConges(){
		conges=autorisationCongeServiceImpl.getAllconges();
		return conges;}
	
	public String addAutoristationConge(Conge con) throws MalformedURLException, IOException {
	

		
		System.out.println("congeeeeee"+con.getMotifs());

		String filname = creerDoc(con);
		System.out.println("Fillllle name" + filname);

		String navigateTo = "/pages/Document/showautorisaionConge?faces-redirect=true"; 
		return navigateTo;
	}
	
	public String creerDoc(Conge con) throws MalformedURLException, IOException {
		
		
		AutorisationConge ac=new AutorisationConge();
		ac.setTitre("AUTORISATION DE CONGÉ");
		Document document = new Document();
		Date d = new Date();
		Date date1 = new Date();
		SimpleDateFormat simpleFormat = new SimpleDateFormat("HHmmss");
		String aa = simpleFormat.format(date1);
	
		filleNaMe = aa + "Autorisation De Conge.pdf";
		String fileName = "C:/wamp64/www/itext/AutorisationDeConge/"+ filleNaMe;
		

		try {		
			@SuppressWarnings("unused")
			PdfWriter pdfWriter = PdfWriter.getInstance(document, new FileOutputStream(fileName));
			document.open();
			System.out.println("Doooooooooooooooooooc");
			Image img = Image.getInstance("C:/wamp64/www/itext/image/Logo.jpeg");
			img.scaleToFit(150, 150);
			document.add(img);

			FontSelector selector1 = new FontSelector();
			Font f1 = FontFactory.getFont(FontFactory.TIMES_ROMAN, 25);
			f1.setColor(BaseColor.BLUE);
			selector1.addFont(f1);
			Phrase ph = selector1.process(ac.getTitre());
			Phrase phrase = new Phrase();
			phrase.add(ac.getTitre());
			
			Paragraph p = new Paragraph();
			p.add(ph);
			p.setSpacingBefore(50);
			p.setAlignment(Element.ALIGN_CENTER);

			document.add(p);
			System.out.println("Documeneeeet");
		
			String nomemploy=con.getEmploye().getNom();
			String prenoemploye=con.getEmploye().getPrenom();
			String motifcon=con.getMotifs();
			String raisoncon=con.getRaison();
			
			ac.setDateCreation(new Date());
			ac.setDescription(nomemploy+" "+prenoemploye+" "+motifcon+" "+raisoncon);
			System.out.println("Documeneeeet 2222222");
			Employe e = employeServiceImpl.find(con.getEmploye().getCin());
			ac.setEmploye(e);
			
			ac.setObjectif(filleNaMe);
			autoris=autorisationCongeServiceImpl.add(ac);
			System.out.println("Documeneeeet33333333333");
			
			Paragraph phrase1 = new Paragraph();
			phrase1.add(" Nom et prénom : "+nomemploy+" "+prenoemploye);
			phrase1.setSpacingBefore(100);
			SimpleDateFormat simpleFormat2 = new SimpleDateFormat("dd/MM/yyyy");
			String aaa = simpleFormat2.format(con.getDateDebut());
			
			String aaaa = simpleFormat2.format(con.getDateFin());

			Paragraph phrase2 = new Paragraph();
			phrase2.add(" Période : du : "+aaa);
			phrase2.setSpacingBefore(15);
			
			
			
			Paragraph phrase3 = new Paragraph();
			phrase3.add("                 au : "+aaaa);
			phrase3.setSpacingBefore(15);
			
			
			Paragraph phrase4 = new Paragraph();
			phrase4.add("Motifs du congé : "+con.getMotifs());
			phrase4.setSpacingBefore(15);
			
			
			
			Paragraph phrase5 = new Paragraph();
			phrase5.add("Raison du congé : "+con.getRaison());
			phrase5.setSpacingBefore(15);
			
			Paragraph phrase6 = new Paragraph();
			phrase6.add("Avis et Signature du responsable : ");
			phrase6.setSpacingBefore(220);
			phrase6.setAlignment(Element.ALIGN_RIGHT);
			
			
			
			document.add(phrase1);
			document.add(phrase2);
			document.add(phrase3);
			document.add(phrase4);
			document.add(phrase5);
			document.add(phrase6);
			
			document.close();
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (DocumentException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		
	
		return filleNaMe;
	}
	
	public StreamedContent getTempPdfFile() throws IOException {

		String name=AutorisationDeCongeBean.autoris.getObjectif();
		System.out.println("nameeeeeeeeeee"+name);
		File testPdfFile = new File("C:/wamp64/www/itext/AutorisationDeConge/"+name);
		return new DefaultStreamedContent(new FileInputStream(testPdfFile), "application/pdf", "test.pdf");
	}
	

	
}

NeoXamPiDev-web/src/main/webapp/pages/Document/AddAutorisationConge.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/template/template.xhtml" xmlns:p="http://primefaces.org/ui">
	<ui:param name="page_name" value="NeoXam-Ajouter Projet" />
	<ui:param name="param_page" value="Ajouter Autorisation Conge" />

	<ui:define name="ContainerPI">



		<p:panel header="Ajouter Autorisation De Conge ">
			<h:panelGrid columns="2" columnClasses="label, value">

				<h:form>
					<p:dataTable var="conge"
						value="#{AutorisationCongeBean.allConges()}">
						<p:column headerText="Id">
							<h:outputText value="#{conge.idConge}" />
						</p:column>

						<p:column headerText="Motifs">
							<h:outputText value="#{conge.motifs}" />
						</p:column>

						<p:column headerText="Raison">
							<h:outputText value="#{conge.raison}" />
						</p:column>

						<p:column headerText="Type">
							<h:outputText value="#{conge.type}" />
						</p:column>

						<p:column>
							<p:commandButton value="Traiter Autorisation Conge"
								action="#{AutorisationCongeBean.addAutoristationConge()}" />
						</p:column>

					</p:dataTable>
				</h:form>
				<!-- 					<h:outputText value="Choisir le Conge " /> -->

				<!-- 					<h:selectOneMenu value="#{AutorisationCongeBean.idConge}"> -->
				<!-- 						<f:selectItem itemLabel="Choisir Conge" itemValue="" /> -->
				<!-- 						<f:selectItems value="#{AutorisationCongeBean.allConges()}" -->
				<!-- 							var="empl" itemValue="#{empl.idConge}" -->
				<!-- 							itemLabel="#{empl.idConge}" /> -->
				<!-- 					</h:selectOneMenu> -->
				<!-- 					<p:commandButton value="Save" -->
				<!-- 						action="#{AutorisationCongeBean.addAutoristationConge()}" /> -->
			</h:panelGrid>
		</p:panel>


	</ui:define>



</ui:composition>

NeoXamPiDev-web/src/main/webapp/pages/Document/AddDocument.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/template/template.xhtml" xmlns:p="http://primefaces.org/ui">
	<ui:param name="page_name" value="Connexion" />
	<ui:param name="param_page" value="Ajouter Document" />

	<ui:define name="ContainerPI">
		<div class="row">
			<div class="col-md-6 col-xl-4">
				<div class="mini-stat clearfix bg-white">

					<div class="mini-stat-info text-right text-muted">
						<span class="counter text-danger">Attestation de travail </span>

					</div>
					<p class="mb-0 m-t-20 text-muted">

						<p:button icon="ui-icon-plus"
							title="traiter attestation de travail">
							<f:param name="productId" value="30" />
						</p:button>
						<span class="pull-right"><i class="fa fa-caret-up m-r-5"></i>10.25%</span>
					</p>
				</div>
			</div>
			<div class="col-md-6 col-xl-4">
				<div class="mini-stat clearfix bg-success">

					<div class="mini-stat-info text-right text-white">
						<span class="counter text-white">Attestation de stage</span>

					</div>
					<p class="mb-0 m-t-20 text-light">
						<p:button icon="ui-icon-plus" title="traiter attestation de stage">
							<f:param name="productId" value="30" />
						</p:button>
						<span class="pull-right"><i class="fa fa-caret-up m-r-5"></i>10.25%</span>
					</p>
				</div>
			</div>

			<div class="col-md-6 col-xl-4">
				<div class="mini-stat clearfix bg-white">

					<div class="mini-stat-info text-right text-muted">
						<span class="counter text-warning">Autorisation de conge</span>

					</div>
					<p class="mb-0 m-t-20 text-muted">
						<p:button icon="ui-icon-plus"
							title="traiter autorisation de conge">
							<f:param name="productId" value="30" />
						</p:button>
						<span class="pull-right"><i class="fa fa-caret-up m-r-5"></i>10.25%</span>
					</p>
				</div>
			</div>

		</div>
<f:view transient="true">
		<h:form>

			<p:panel header="Ajouter Attestation De Travail ">
				<h:panelGrid columns="2" columnClasses="label, value">
					<!-- 			<div class="row"> -->
					<!-- 						<div class="col-md-12 col-xl-9"> -->


					<h:outputText value="" />

					<h:outputText value="Choisir le Responsable " />
					<h:selectOneMenu value="#{attestationDeTravailBean.cinn2}">
						<f:selectItem itemLabel="Choisir Responsable" itemValue="" />
						<f:selectItems value="#{attestationDeTravailBean.allemployeRH}"
							var="empl" itemValue="#{empl.cin}" itemLabel="#{empl.nom}" />
					</h:selectOneMenu>
					<!-- 				</div> -->
					<!-- 						<div class="col-md-12 col-xl-9"> -->
					<h:outputText value="" />
					<h:outputText value="Choisir l'emploie " />
					<h:selectOneMenu value="#{attestationDeTravailBean.cinn}">
						<f:selectItem itemLabel="Choisir employé" itemValue="" />
						<f:selectItems value="#{attestationDeTravailBean.allemploye}"
							var="empl" itemValue="#{empl.cin}" itemLabel="#{empl.nom}" />
					</h:selectOneMenu>
					<!-- 				</div> -->

					<!-- 				<div class="col-md-12 col-xl-9"> -->
					<p:commandButton value="Save"
						action="#{attestationDeTravailBean.addDocumentAttestationDeTravail()}" />
					<!-- 				</div> -->
					<!-- 			</div> -->
				</h:panelGrid>
			</p:panel>
		</h:form>
</f:view>

		<p:panel header="Ajouter Autorisation De Conge ">
			<h:panelGrid columns="2" columnClasses="label, value">

				<h:form>
					<p:dataTable var="conge"
						value="#{AutorisationCongeBean.allConges()}">
						<p:column headerText="Id">
							<h:outputText value="#{conge.idConge}" />
						</p:column>

						<p:column headerText="Motifs">
							<h:outputText value="#{conge.motifs}" />
						</p:column>

						<p:column headerText="Raison">
							<h:outputText value="#{conge.raison}" />
						</p:column>

						<p:column headerText="Employe">
							<h:outputText value="#{conge.employe.nom}" />
						</p:column>
						<p:column>
							<p:commandButton value="Traiter Autorisation Conge"
								action="#{AutorisationCongeBean.addAutoristationConge(conge)}" />
						</p:column>

					</p:dataTable>
				</h:form>
			</h:panelGrid>
		</p:panel>


	</ui:define>

</ui:composition>

NeoXamPiDev-web/src/main/webapp/pages/Document/ShowDocument.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"     xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"     template="/template/template.xhtml" xmlns:p="http://primefaces.org/ui">
<ui:param name="page_name" value="Show Doc" />
<ui:param name="param_page" value="Show Document" />

<ui:define name="ContainerPI">
        <div>
          <p:media value="#{attestationDeTravailBean.tempPdfFile}" width="100%" height="500px"
            cache="false" player="pdf"/>
        </div>



</ui:define>
      
</ui:composition>

NeoXamPiDev-web/src/main/webapp/pages/Document/showautorisaionConge.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"     xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"     template="/template/template.xhtml" xmlns:p="http://primefaces.org/ui">
<ui:param name="page_name" value="Show Doc" />
<ui:param name="param_page" value="Show Document" />

<ui:define name="ContainerPI">
        <div>
          <p:media value="#{AutorisationCongeBean.tempPdfFile}" width="100%" height="500px"
            cache="false" player="pdf"/>
        </div>

</ui:define>
      
</ui:composition>